(cl:in-package mpc_icra-msg)
(cl:export '(X_L-VAL
          X_L
          Y_L-VAL
          Y_L
          Z_L-VAL
          Z_L
          ROLL_Q-VAL
          ROLL_Q
          PITCH_Q-VAL
          PITCH_Q
          YAW_Q-VAL
          YAW_Q
          P_X-VAL
          P_X
          P_Y-VAL
          P_Y
          P_Z-VAL
          P_Z
          VX_L-VAL
          VX_L
          VY_L-VAL
          VY_L
          VZ_L-VAL
          VZ_L
          P_Q-VAL
          P_Q
          Q_Q-VAL
          Q_Q
          R_Q-VAL
          R_Q
          W_X-VAL
          W_X
          W_Y-VAL
          W_Y
          W_Z-VAL
          W_Z
          LENGTH-VAL
          LENGTH
))